const $ = (s)=>document.querySelector(s);
const $$ = (s)=>Array.from(document.querySelectorAll(s));
const state = { outline: [], selectedTemplate:null, isMember:false, lastCoverData:null };

const builtInTemplates = [
  {id:'owned-medical', name:'Healthcare Training Pro', category:'medical', source:'owned', credit:'自有設計', colors:['#2563eb','#facc15','#eff6ff'], visual:'medical', desc:'醫療培訓、診所項目、健康趨勢。'},
  {id:'owned-career', name:'Career Steps 3D', category:'business', source:'owned', credit:'自有設計', colors:['#335c81','#f7c978','#eaf3fb'], visual:'career', desc:'商務培訓、職業發展、方案路線。'},
  {id:'owned-blackgold', name:'Investor Black Gold', category:'finance', source:'owned', credit:'自有設計', colors:['#050505','#d4af37','#111827'], visual:'blackgold', desc:'投資路演、商業計劃、高端匯報。'},
  {id:'owned-public', name:'Public Policy Whitepaper', category:'public', source:'owned', credit:'自有設計', colors:['#0b1d35','#d6a43a','#f7f1e6'], visual:'public', desc:'政府簡報、白皮書、公共價值提案。'},
  {id:'owned-tech', name:'Quantum AI Gradient', category:'tech', source:'owned', credit:'自有設計', colors:['#6d28d9','#38bdf8','#faf5ff'], visual:'quantum', desc:'AI 科技、產品發佈、創新方案。'},
  {id:'owned-cat', name:'Warm Cat Welfare', category:'public', source:'owned', credit:'自有設計', colors:['#f97316','#7c2d12','#fff7ed'], visual:'cat', desc:'公益、生命教育、社區項目。'}
];

function escapeXml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&apos;','"':'&quot;'}[c]));}
function short(s,n=44){s=String(s||''); return s.length>n?s.slice(0,n-1)+'…':s;}
function slug(s){return String(s||'ppt').replace(/[\\/:*?"<>|\s]+/g,'-').slice(0,42)||'ppt';}
function getImportedTemplates(){try{return JSON.parse(localStorage.getItem('realTemplateCloud')||'[]')}catch{return []}}
function setImportedTemplates(arr){localStorage.setItem('realTemplateCloud',JSON.stringify(arr));}
function allTemplates(){return [...getImportedTemplates(), ...builtInTemplates];}

function svgData(w,h,body){return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="14" stdDeviation="14" flood-color="#0f172a" flood-opacity=".18"/></filter><linearGradient id="neon" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#a855f7"/><stop offset="1" stop-color="#38bdf8"/></linearGradient></defs>${body}</svg>`)}
function templateCover(t){
 if(t.coverData) return t.coverData;
 const [a,b,c]=t.colors; let body='';
 if(t.visual==='medical') body=`<rect width="720" height="405" fill="#f8fafc"/><rect x="360" width="360" height="405" fill="#386bd7"/><rect x="54" y="72" width="382" height="210" rx="18" fill="#fff" filter="url(#shadow)"/><circle cx="535" cy="155" r="52" fill="#cbd5e1"/><path d="M445 315 q90-145 180 0" fill="#e2e8f0"/><text x="86" y="150" font-size="50" font-weight="900" fill="#111827">Medical</text><text x="86" y="210" font-size="50" font-weight="900" fill="#111827">Training</text><text x="86" y="255" font-size="22" fill="#64748b">Professional workshop deck</text><path d="M650 0 L720 0 L720 80 Z" fill="#facc15"/>`;
 else if(t.visual==='career') body=`<rect width="720" height="405" fill="#335c81"/><path d="M80 305 h210 v-28 H120 v-32h150v-32H160v-32h100" stroke="#9fc3de" stroke-width="38" fill="none"/><circle cx="405" cy="115" r="50" fill="#f7c978"/><path d="M350 310 L405 150 L465 310 Z" fill="#071426"/><text x="500" y="150" font-size="50" font-weight="900" fill="#fff">Career</text><text x="500" y="210" font-size="50" font-weight="900" fill="#fff">Steps</text>`;
 else if(t.visual==='blackgold') body=`<rect width="720" height="405" fill="#070707"/><circle cx="592" cy="84" r="128" fill="#d4af37" opacity=".25"/><path d="M0 405 L720 150 L720 405Z" fill="#d4af37" opacity=".12"/><text x="58" y="122" font-size="42" font-weight="900" fill="#d4af37">INVESTOR</text><text x="58" y="190" font-size="70" font-weight="900" fill="#fff">ROADSHOW</text><rect x="58" y="238" width="260" height="10" fill="#d4af37"/><text x="58" y="292" font-size="20" fill="#e8d8a3">Premium pitch deck</text>`;
 else if(t.visual==='public') body=`<rect width="720" height="405" fill="#f7f1e6"/><rect width="720" height="22" fill="#0b1d35"/><rect y="22" width="260" height="7" fill="#d6a43a"/><path d="M425 288 h210 v-34h-210zM456 254v-96h22v96M516 254v-96h22v96M576 254v-96h22v96M440 153h170l-85-55z" fill="#0b1d35"/><text x="58" y="128" font-size="50" font-weight="900" fill="#0b1d35">PUBLIC POLICY</text><text x="58" y="190" font-size="50" font-weight="900" fill="#0b1d35">WHITE PAPER</text><rect x="58" y="248" width="280" height="9" fill="#d6a43a"/>`;
 else if(t.visual==='quantum') body=`<rect width="720" height="405" fill="#faf5ff"/><circle cx="360" cy="202" r="185" fill="url(#neon)" opacity=".18"/><path d="M115 285 C210 70 350 370 610 90" stroke="url(#neon)" stroke-width="16" fill="none" opacity=".75"/><polygon points="386,110 450,180 410,285 320,260 300,160" fill="#a78bfa" opacity=".55"/><text x="65" y="170" font-size="58" font-weight="900" fill="#6d28d9">QUANTUM</text><text x="65" y="238" font-size="58" font-weight="900" fill="#6d28d9">AI DECK</text>`;
 else if(t.visual==='cat') body=`<rect width="720" height="405" fill="#fff7ed"/><circle cx="590" cy="105" r="130" fill="#fed7aa"/><circle cx="160" cy="190" r="75" fill="#f97316"/><path d="M110 150 L130 105 L155 145 M205 145 L235 105 L232 160" fill="#f97316"/><circle cx="142" cy="185" r="10" fill="#fff"/><circle cx="180" cy="185" r="10" fill="#fff"/><path d="M120 230 Q160 260 200 230" stroke="#fff" stroke-width="7" fill="none"/><text x="310" y="145" font-size="48" font-weight="900" fill="#7c2d12">CAT WELFARE</text><text x="310" y="205" font-size="38" font-weight="900" fill="#f97316">LIFE EDUCATION</text><rect x="310" y="245" width="260" height="12" fill="#fed7aa"/>`;
 else body=`<rect width="720" height="405" fill="${c}"/><circle cx="575" cy="105" r="120" fill="${b}" opacity=".3"/><text x="58" y="170" font-size="58" font-weight="900" fill="${a}">${escapeXml(t.name)}</text>`;
 return svgData(720,405,body);
}

function buildOutline(){
 const topic=$('#topicInput').value.trim()||'未命名簡報'; const scene=$('#sceneSelect').value; const n=Number($('#pageCount').value);
 const scenes={public:['項目定位與公共價值','現況痛點與政策背景','目標對象與服務場景','核心方案與空間/流程設計','治理機制與監管透明度','實施路徑與階段里程碑','資源配置與成本收益','風險控制與可持續營運','KPI 指標與社會影響','下一步行動'],gov:['匯報背景與政策契合','現況問題與治理需要','總體目標與原則','方案架構與工作機制','跨部門協作路徑','監管與數據透明','階段成果與預期效益','資源需求與風險控制','落地時間表','決策事項'],biz:['市場機會','用戶痛點','產品方案','商業模式','競爭優勢','收入模型','推廣策略','團隊與資源','里程碑','合作/融資需求'],medical:['臨床/服務背景','目標人群','核心服務流程','設備與數據管理','風險與合規','運營配置','成效指標','推廣方案','成本收益','下一步'],finance:['宏觀背景','市場數據','核心觀察','風險因素','策略建議','資產配置','收益假設','情境分析','執行時間表','結論'],tech:['問題場景','AI 解決方案','產品能力','技術架構','使用流程','安全與成本','商業化路徑','示範案例','迭代規劃','下一步']};
 const base=scenes[scene]||scenes.public; state.outline=base.slice(0,n).map((title,i)=>({title, subtitle:`圍繞「${topic}」展開的第 ${i+1} 頁重點說明`, bullets:[`${title}的核心重點`,`與目標受眾相關的價值`,`可以落地執行的行動項`]}));
 renderOutline(); showPanel('outlinePanel');
}
function renderOutline(){ $('#outlineList').innerHTML=state.outline.map((it,i)=>`<div class="outline-item"><b>${i+1}. ${it.title}</b><span>${it.subtitle}</span></div>`).join(''); }
function renderTemplates(){ const filter=$('#styleFilter').value; let data=allTemplates(); if(filter!=='all') data=data.filter(t=>t.source===filter||t.category===filter); $('#emptyTemplates').classList.toggle('hidden', data.length>0); $('#templateGrid').innerHTML=data.map(t=>`<article class="tpl-card" data-id="${t.id}"><img class="tpl-cover" src="${templateCover(t)}"/><div class="tpl-info"><div class="badges"><span class="badge ${t.source}">${t.source==='licensed'?'白名單授權':t.source==='owned'?'自有模板':'用戶導入'}</span><span class="badge">${labelCategory(t.category)}</span></div><h3>${t.name}</h3><p>${t.desc||'真實模板封面 / 授權記錄已保存。'}</p><div class="card-actions"><button class="apply" data-id="${t.id}">套用模板</button><button class="preview" data-id="${t.id}">預覽</button></div></div></article>`).join('');
 $$('.apply,.preview,.tpl-card').forEach(el=>el.onclick=(e)=>{ const id=e.currentTarget.dataset.id || e.target.dataset.id; if(!id) return; selectTemplate(id); }); }
function labelCategory(c){return {medical:'醫療',business:'商務',public:'政府/公益',tech:'科技',finance:'金融',education:'教育'}[c]||c}
function selectTemplate(id){ state.selectedTemplate=allTemplates().find(t=>t.id===id); renderPreview(); showPanel('previewPanel'); }
function renderPreview(){ const tpl=state.selectedTemplate||allTemplates()[0]; const cover=templateCover(tpl); $('#previewStrip').innerHTML=state.outline.map((it,i)=>`<div class="slide-thumb"><img src="${i===0?cover:slideThumb(tpl,it,i)}"/><div class="slide-caption"><b>${i+1}. ${it.title}</b><span>${short(it.subtitle,70)}</span></div></div>`).join(''); }
function slideThumb(tpl,it,i){ const [a,b,c]=tpl.colors||['#071426','#0f4cbd','#fff']; const dark=['blackgold'].includes(tpl.visual); const bg=dark?'#080808':(tpl.category==='public'?'#f7f1e6':'#ffffff'); const ink=dark?'#fff':'#071426'; const body=`<rect width="720" height="405" fill="${bg}"/><rect width="720" height="44" fill="${dark?b:a}" opacity="${dark?'.9':'1'}"/><circle cx="620" cy="105" r="90" fill="${b}" opacity=".22"/><text x="58" y="130" font-size="38" font-weight="900" fill="${ink}">${escapeXml(short(it.title,22))}</text><rect x="58" y="180" width="260" height="70" rx="18" fill="${dark?'#1f2937':'#f8fafc'}"/><rect x="360" y="180" width="260" height="70" rx="18" fill="${dark?'#1f2937':'#f8fafc'}"/><rect x="88" y="208" width="150" height="10" rx="5" fill="${dark?'#6b7280':'#cbd5e1'}"/><rect x="88" y="232" width="105" height="8" rx="4" fill="${dark?'#4b5563':'#dbe3ee'}"/><rect x="390" y="208" width="150" height="10" rx="5" fill="${dark?'#6b7280':'#cbd5e1'}"/><rect x="390" y="232" width="105" height="8" rx="4" fill="${dark?'#4b5563':'#dbe3ee'}"/><rect x="58" y="305" width="520" height="12" rx="6" fill="${b}" opacity=".35"/><text x="58" y="360" font-size="20" fill="${dark?'#d1d5db':'#475467'}">${escapeXml(short(it.subtitle,55))}</text>`; return svgData(720,405,body); }

function showPanel(id){ $$('.panel').forEach(p=>p.classList.add('hidden')); $('#'+id).classList.remove('hidden'); $$('.nav-item').forEach(b=>b.classList.toggle('active', b.dataset.panel===id)); window.scrollTo({top:0,behavior:'smooth'}); if(id==='templatePanel') renderTemplates(); }

function saveImported(){ const name=$('#tplName').value.trim(); const credit=$('#tplCredit').value.trim(); if(!name) return alert('請先填模板名稱'); if(!state.lastCoverData) return alert('請先上傳真實模板封面圖'); const arr=getImportedTemplates(); arr.unshift({id:'imp-'+Date.now(),name,category:$('#tplCategory').value,source:$('#tplSource').value,credit,coverData:state.lastCoverData,colors:['#071426','#0f4cbd','#ffffff'],visual:'imported',desc: credit || '已導入真實模板封面'}); setImportedTemplates(arr); state.lastCoverData=null; $('#importPreview').innerHTML=''; $('#tplName').value=''; $('#tplCredit').value=''; renderTemplates(); alert('已保存到本地模板雲庫'); closeAdmin(); }
function openAdmin(){ $('#adminModal').classList.remove('hidden'); }
function closeAdmin(){ $('#adminModal').classList.add('hidden'); }

async function downloadPptx(){ if(!state.selectedTemplate) return alert('請先選擇模板'); if(!window.pptxgen) return alert('PPTX 引擎未載入'); if(!state.isMember){ $('#memberModal').classList.remove('hidden'); return; } const tpl=state.selectedTemplate; const topic=$('#topicInput').value.trim()||'AI PPT Studio'; const pptx=new pptxgen(); pptx.layout='LAYOUT_WIDE'; pptx.author='AI PPT Studio Cloud'; const [a,b,c]=tpl.colors||['#071426','#0f4cbd','#ffffff']; for(let i=0;i<state.outline.length;i++){ const item=state.outline[i]; const slide=pptx.addSlide(); slide.background={color:(tpl.visual==='blackgold'?'080808':(tpl.category==='public'?'F7F1E6':'FFFFFF'))}; if(i===0){ try{ slide.addImage({data:templateCover(tpl),x:0,y:0,w:13.333,h:7.5}); slide.addShape(pptx.ShapeType.rect,{x:.55,y:5.75,w:7.2,h:.8,fill:{color:'FFFFFF',transparency:6},line:{color:'FFFFFF',transparency:100},radius:.12}); slide.addText(topic,{x:.75,y:5.95,w:6.9,h:.35,fontFace:'Aptos Display',fontSize:22,bold:true,color:'071426',fit:'shrink'}); }catch{ slide.addText(topic,{x:.8,y:1,w:11.8,h:1.4,fontSize:38,bold:true,color:a.replace('#','')}); } } else { const dark=tpl.visual==='blackgold'; slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:.35,fill:{color:(dark?b:a).replace('#','')},line:{color:(dark?b:a).replace('#','')}}); slide.addText(item.title,{x:.7,y:.85,w:11.8,h:.6,fontFace:'Aptos Display',fontSize:30,bold:true,color:(dark?'FFFFFF':'071426')}); slide.addText(item.subtitle,{x:.72,y:1.55,w:10.8,h:.38,fontSize:13,color:(dark?'D1D5DB':'667085')}); item.bullets.forEach((txt,idx)=>{ slide.addShape(pptx.ShapeType.roundRect,{x:.9,y:2.25+idx*.85,w:10.8,h:.55,rectRadius:.08,fill:{color:(dark?'1F2937':'F8FAFC')},line:{color:(dark?'374151':'E2E8F0')}}); slide.addText('• '+txt,{x:1.15,y:2.39+idx*.85,w:10.2,h:.2,fontSize:15,bold:true,color:(dark?'FFFFFF':'0F172A')}); }); slide.addText(String(i+1).padStart(2,'0'),{x:11.5,y:6.55,w:1,h:.3,fontSize:14,bold:true,color:(dark?'D4AF37':b.replace('#',''))}); } } const credit=tpl.credit||''; if(credit && tpl.source!=='owned'){ const s=pptx.addSlide(); s.background={color:'FFFFFF'}; s.addText('Credits / 授權說明',{x:.8,y:1,w:11,h:.5,fontSize:28,bold:true,color:'071426'}); s.addText(`Template credit: ${credit}\nSource type: ${tpl.source}\nThis page is automatically retained for attribution/licensing record.`,{x:.85,y:1.9,w:11,h:2,fontSize:16,color:'334155',breakLine:false}); }
 await pptx.writeFile({fileName:`${slug(topic)}-${slug(tpl.name)}.pptx`}); }

$('#charCount').oninput=null; $('#topicInput').addEventListener('input',e=>$('#charCount').textContent=e.target.value.length+' 字');
$('#generateBtn').onclick=buildOutline; $('#editOutlineBtn').onclick=()=>showPanel('createPanel'); $('#goTemplateBtn').onclick=()=>showPanel('templatePanel'); $('#backOutlineBtn').onclick=()=>showPanel('outlinePanel'); $('#changeTemplateBtn').onclick=()=>showPanel('templatePanel'); $('#downloadBtn').onclick=downloadPptx; $('#styleFilter').onchange=renderTemplates;
$('#adminBtn').onclick=openAdmin; $('#openImporterBtn').onclick=openAdmin; $('#closeAdmin').onclick=closeAdmin; $('#saveTemplateBtn').onclick=saveImported; $('#clearTemplatesBtn').onclick=()=>{ if(confirm('確定清空本地導入模板？')){localStorage.removeItem('realTemplateCloud'); renderTemplates();} };
$('#coverFile').onchange=(e)=>{ const f=e.target.files[0]; if(!f) return; const r=new FileReader(); r.onload=()=>{state.lastCoverData=r.result; $('#importPreview').innerHTML=`<img src="${r.result}" alt="cover preview"/>`;}; r.readAsDataURL(f); };
$('#loginBtn').onclick=()=>alert('已模擬登入。正式版後續接 Supabase / Firebase / 自建後台。'); $('#memberBtn').onclick=()=>$('#memberModal').classList.remove('hidden'); $('#closeMember').onclick=()=>$('#memberModal').classList.add('hidden'); $('#fakePayBtn').onclick=()=>{state.isMember=true; $('#memberModal').classList.add('hidden'); alert('已模擬開通會員，現在可以下載 PPTX。')};
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active')); b.classList.add('active')});
$$('.nav-item').forEach(b=>b.onclick=()=>{ const p=b.dataset.panel; if(p==='member') return $('#memberModal').classList.remove('hidden'); if(p==='admin') return openAdmin(); if(p==='templatePanel' && state.outline.length===0) return alert('請先輸入內容並生成大綱，再選擇模板。'); if(p==='account') return alert('帳戶頁後續接真實登入。'); showPanel(p); });
renderTemplates();
if('serviceWorker' in navigator){ navigator.serviceWorker.register('./sw.js').catch(()=>{}); }
