const $=(s)=>document.querySelector(s), $$=(s)=>Array.from(document.querySelectorAll(s));
const state={outline:[],selectedTemplate:null,isMember:false,lastCoverData:null,lastTemplateFile:null,externalTemplates:[],templateTab:'external'};
const sceneTitles={public:['项目定位与公共价值','现状痛点与政策背景','目标对象与服务场景','核心方案与流程设计','治理机制与透明度','实施路径与里程碑','资源配置与成本收益','风险控制与可持续运营','KPI 与社会影响','下一步行动'],gov:['汇报背景与政策契合','现况问题与治理需要','总体目标与原则','方案架构与工作机制','跨部门协作路径','监管与数据透明','阶段成果与预期效益','资源需求与风险控制','落地时间表','决策事项'],biz:['市场机会','用户痛点','产品方案','商业模式','竞争优势','收入模型','推广策略','团队与资源','里程碑','合作/融资需求'],medical:['临床/服务背景','目标人群','核心服务流程','设备与数据管理','风险与合规','运营配置','成效指标','推广方案','成本收益','下一步']};
function getImportedTemplates(){try{return JSON.parse(localStorage.getItem('realTemplateCloud')||'[]')}catch{return []}}
function setImportedTemplates(a){localStorage.setItem('realTemplateCloud',JSON.stringify(a));}
const isRealTemplate=(t)=>Boolean(t&&t.coverData&&t.templateData&&['pptx','potx'].includes(t.templateExt));
const short=(s,n=42)=>String(s||'').length>n?String(s).slice(0,n-1)+'…':String(s||'');
function splitLongText(t){return t.split(/\n+|[。！？!?；;]+/).map(s=>s.trim()).filter(Boolean);}
function buildOutline(){const topic=$('#topicInput').value.trim()||'未命名简报';const scene=$('#sceneSelect').value;const n=Number($('#pageCount').value);const base=(sceneTitles[scene]||sceneTitles.public).slice(0,n);const seg=splitLongText(topic);const theme=topic.slice(0,30);state.outline=base.map((title,i)=>{const s1=seg[(i*2)%Math.max(seg.length,1)]||theme;const s2=seg[(i*2+1)%Math.max(seg.length,1)]||`${title}执行重点`;const s3=seg[(i*2+2)%Math.max(seg.length,1)]||`${title}成果`;return{title,subtitle:`聚焦：${short(s1,30)}`,bullets:[`关键结论：${short(s1,36)}`,`推进动作：${short(s2,36)}`,`交付成果：${short(s3,36)}`]};});renderOutline();showPanel('outlinePanel');}
function renderOutline(){$('#outlineList').innerHTML=state.outline.map((it,i)=>`<article class="outline-item"><h3>${i+1}. ${it.title}</h3><p class="outline-sub">${it.subtitle}</p><ul>${it.bullets.map(b=>`<li>${b}</li>`).join('')}</ul></article>`).join('');}
function renderExternalTemplates(){const g=$('#externalTemplateGrid');g.innerHTML=state.externalTemplates.map(t=>`<article class="tpl-card text-only"><div class="tpl-info"><h3>${t.template_name}</h3><p><b>来源：</b>${t.provider} · <b>分类：</b>${t.category}</p><p>${t.description}</p><p><b>访问方式：</b>${t.access_type}</p><p class="license-note">${t.license_note}</p><div class="badges">${(t.tags||[]).map(x=>`<span class="badge">${x}</span>`).join('')}</div><div class="card-actions"><button class="apply ext-go" data-url="${t.source_url}">${t.button_text}</button></div></div></article>`).join('');$$('.ext-go').forEach(b=>b.onclick=()=>window.open(b.dataset.url,'_blank'));}
function dataUrlToBlob(d){const [m,data]=String(d||'').split(',');if(!m||!data)return null;const mime=((m.match(/data:(.*?);base64/)||[])[1])||'application/octet-stream';const bin=atob(data);const arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:mime});}
function renderMyTemplates(){const list=getImportedTemplates().filter(isRealTemplate),g=$('#myTemplateGrid'),e=$('#myTemplateEmpty');e.classList.toggle('hidden',list.length>0);g.innerHTML=list.map(t=>`<article class="tpl-card"><img class="tpl-cover" src="${t.coverData}"/><div class="tpl-info"><h3>${t.name}</h3><p>${t.credit||'已导入真实模板'}</p><div class="card-actions"><button class="apply mine-dl" data-id="${t.id}">下载我的模板 PPTX</button></div></div></article>`).join('');$$('.mine-dl').forEach(b=>b.onclick=(e)=>{const id=e.target.dataset.id;state.selectedTemplate=list.find(x=>x.id===id);downloadPptx();});}
function renderTemplateTabs(){$$('.tpl-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.templateTab));$('#externalTemplateArea').classList.toggle('hidden',state.templateTab!=='external');$('#myTemplateArea').classList.toggle('hidden',state.templateTab!=='mine');if(state.templateTab==='external')renderExternalTemplates();else renderMyTemplates();}
function showPanel(id){$$('.panel').forEach(p=>p.classList.add('hidden'));$('#'+id).classList.remove('hidden');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));if(id==='templatePanel')renderTemplateTabs();window.scrollTo({top:0,behavior:'smooth'});}
function triggerDownload(blob,f){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=f;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200);}
async function downloadPptx(){if(!state.selectedTemplate)return alert('请先选择模板');if(!state.isMember){$('#memberModal').classList.remove('hidden');return;}const tpl=state.selectedTemplate;const blob=dataUrlToBlob(tpl.templateData);if(!blob)return alert('模板文件损坏，请重新导入。');triggerDownload(blob,`${(tpl.name||'template').replace(/[\/:*?"<>|\s]+/g,'-')}.${tpl.templateExt}`);}
function saveImported(){const name=$('#tplName').value.trim(),credit=$('#tplCredit').value.trim();if(!name)return alert('请先填模板名称');if(!state.lastTemplateFile)return alert('请先上传 PPTX/POTX');if(!state.lastCoverData)return alert('请先上传封面图');const arr=getImportedTemplates();arr.unshift({id:'imp-'+Date.now(),name,category:$('#tplCategory').value,source:$('#tplSource').value,credit,coverData:state.lastCoverData,templateData:state.lastTemplateFile.data,templateExt:state.lastTemplateFile.ext,templateMime:state.lastTemplateFile.mime});setImportedTemplates(arr);alert('已成功导入到“我的真模板库”。现在可以在模板页选择并下载自己的真实 PPTX/POTX。');$('#adminModal').classList.add('hidden');renderMyTemplates();}
async function loadExternalTemplates(){try{const r=await fetch(`./templates/external_templates.json?v=${Date.now()}`,{cache:'no-store'});state.externalTemplates=await r.json();}catch{state.externalTemplates=[];}}
$('#topicInput').addEventListener('input',e=>$('#charCount').textContent=e.target.value.length+' 字');
$('#generateBtn').onclick=buildOutline;$('#editOutlineBtn').onclick=()=>showPanel('createPanel');$('#goTemplateBtn').onclick=()=>{state.templateTab='external';showPanel('templatePanel')};$('#backOutlineBtn').onclick=()=>showPanel('outlinePanel');
$('#adminBtn').onclick=()=>$('#adminModal').classList.remove('hidden');$('#openImporterBtn').onclick=()=>$('#adminModal').classList.remove('hidden');$('#closeAdmin').onclick=()=>$('#adminModal').classList.add('hidden');$('#saveTemplateBtn').onclick=saveImported;$('#clearTemplatesBtn').onclick=()=>{if(confirm('确定清空本地导入模板？')){localStorage.removeItem('realTemplateCloud');renderMyTemplates();}};
$('#coverFile').onchange=(e)=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.lastCoverData=r.result;$('#importPreview').innerHTML=`<img src="${r.result}" alt="cover"/>`;};r.readAsDataURL(f);};
$('#templateFile').onchange=(e)=>{const f=e.target.files[0];if(!f)return;const ext=((f.name||'').split('.').pop()||'').toLowerCase();if(!['pptx','potx'].includes(ext))return alert('只支持上传 PPTX/POTX');const r=new FileReader();r.onload=()=>state.lastTemplateFile={data:r.result,ext,mime:f.type||''};r.readAsDataURL(f);};
$('#loginBtn').onclick=()=>alert('已模拟登入。');$('#memberBtn').onclick=()=>$('#memberModal').classList.remove('hidden');$('#closeMember').onclick=()=>$('#memberModal').classList.add('hidden');$('#fakePayBtn').onclick=()=>{state.isMember=true;$('#memberModal').classList.add('hidden');};
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$$('.tpl-tab').forEach(b=>b.onclick=()=>{state.templateTab=b.dataset.tab;renderTemplateTabs();});
$$('.nav-item').forEach(b=>b.onclick=()=>{const p=b.dataset.panel;if(p==='member')return $('#memberModal').classList.remove('hidden');if(p==='admin')return $('#adminModal').classList.remove('hidden');if(p==='account')return alert('账户页后续接真实登录。');if(p==='templatePanel'&&state.outline.length===0)return alert('请先输入内容并生成大纲，再选择模板。');showPanel(p);});
loadExternalTemplates().finally(()=>renderTemplateTabs());if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}
